### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pew** [cooperspencer/gickup#47] opened 2021-12-17 05:48 UTC
With the release of v.0.9.8 I'm getting this error after gickup grabbed the list of my GitHub repos:

```
gickup-runner-1  | panic: runtime error: invalid memory address or nil pointer dereference
gickup-runner-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8e5ab4]
gickup-runner-1  |
gickup-runner-1  | goroutine 1 [running]:
gickup-runner-1  | main.Backup({0xc0002e6000, 0xa4, 0x0}, 0xc000136640)
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/main.go:62 +0x2b4
gickup-runner-1  | main.RunBackup(0xc000136640)
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/main.go:92 +0x45
gickup-runner-1  | main.main()
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/main.go:147 +0x71f
gickup-runner-1 exited with code 2
```

It works just fine when I'm using the 0.9.7 Docker tag. Anything else I can provide to debug this?

**Comment by cooperspencer** [comment] 2021-12-17 06:06
I implemented a substitution for `~`and that caused a problem in the docker image. Apparently there is a problem in docker when it tries to get the user. This behavior is fixed in `v0.9.8-1`

**Comment by pew** [comment] 2021-12-17 07:00
Thanks! Pulled the latest image, GitHub works fine. However, it does crash with GitLab now:

```
gickup-runner-1  | panic: runtime error: invalid memory address or nil pointer dereference
gickup-runner-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x760ffa]
gickup-runner-1  |
gickup-runner-1  | goroutine 1 [running]:
gickup-runner-1  | gickup/gitlab.Get(0xc000136640)
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/gitlab/gitlab.go:152 +0x123a
gickup-runner-1  | main.RunBackup(0xc000136640)
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/main.go:131 +0x86
gickup-runner-1  | main.main()
gickup-runner-1  |      /go/src/github.com/cooperspencer/gickup/main.go:175 +0x71f
gickup-runner-1 exited with code 2
```

**Comment by cooperspencer** [comment] 2021-12-17 07:11
I will have a look. I think I already know what the issue is. Be back in a bit

**Comment by cooperspencer** [comment] 2021-12-17 07:26
I got the problem. Group Projects do not return an owner in gitlab...

**Comment by cooperspencer** [comment] 2021-12-17 07:30
pushed a new release for the hotfix in the gitlab groups. Thanks for bringing it to my attention.

**Comment by cooperspencer** [comment] 2021-12-17 07:53
the new containers are now online with tag 0.9.8-2

**Comment by pew** [comment] 2021-12-17 07:59
> the new containers are now online with tag 0.9.8-2

Thank you! Works perfectly now 👍

**Comment by cooperspencer** [comment] 2021-12-17 08:01
Thanks for testing it

**Closed by cooperspencer** 2021-12-17 08:01 UTC
Labels: bug
